### ISSUE TITLE
AttributeError: Can't pickle local object 'main.<locals>.TrainDataset'

### ISSUE THREAD

**Issue by kmust-why** [Herbert95/tianchi_lvcai#5]
PS F:\gan\tianchi_lvcai-master> python .\main_inception_v4.py
Traceback (most recent call last):
  File ".\main_inception_v4.py", line 475, in <module>
    main()
  File ".\main_inception_v4.py", line 427, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File ".\main_inception_v4.py", line 143, in train
    for i, (images, target) in enumerate(train_loader):
  File "C:\Program Files\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 310, in __iter__
    return DataLoaderIter(self)
  File "C:\Program Files\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 167, in __init__
    w.start()
  File "C:\Program Files\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Anaconda3\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Anaconda3\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.TrainDataset'
PS F:\gan\tianchi_lvcai-master> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Anaconda3\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
EOFError: Ran out of input

**Comment by kmust-why** [comment]
这个是pytorch版本的问题吗，我用python3.5,pytorch0.3

**Comment by Lane565** [comment]
Same problem as you. Did you solve it?

**Comment by Lane565** [comment]
一样的问题。我用的python 3.6, pytorch 0.4.1

**Comment by azyslzp** [comment]
一样的问题，我用的python3.6, torch 1.1

**Comment by xjtu-blacksmith** [comment]
Windows 系统上 num_workers 的问题，见 README
